name: Run Octave tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-octave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Octave
        run: sudo apt-get update && sudo apt-get install -y octave

      - name: Run Octave script
        run: |
          octave --eval "disp('Octave is running!');"  # Replace with your own command or script
          octave /path/to/your_script.m  # Replace with the path to your Octave script

      - name: Save output (Optional)
        run: |
          echo "Output from Octave script:"
          cat output.txt  # Replace with your output file