name: Ubuntu CI

on:
  pull_request:
    branches:
      - test
      - main

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set up node
      uses: actions/setup-node@v3
    - name: Print node version
      run: | 
        node --version
        npm --version
    - name: Install dependencies
      run: |
        chmod +x ./scripts/DeveloperSetup.sh
        ./scripts/DeveloperSetup.sh
    - name: Run tests in venv
      run: |
        . ./venv/bin/activate
        pytest
