name: Run Tests on Pull Request (Windows)

on:
  pull_request:
    branches:
      - test
      - main

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: .\scripts\DeveloperSetup.ps1
    - name: Run tests in venv
      run: |
        .\scripts\ActivateVirtualEnvironment.ps1
        pytest
